// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PhoneNumberController from "./phone_number_controller"
application.register("phone-number", PhoneNumberController)

import BlogController from "./blog_controller"
application.register("blog", BlogController)

import HeaderController from "./header_controller"
application.register("header", HeaderController)

import HeaderBlogController from "./header_blog_controller"
application.register("header-blog", HeaderBlogController)

import MenuController from "./blog_controller"
application.register("blog-controller", MenuController)

import Notification from "stimulus-notification"
application.register('notification', Notification)

import AcordionController from "./accordion_controller"
application.register("accordion", AcordionController)

import AnimatedNumber from '@stimulus-components/animated-number'
application.register('animated-number', AnimatedNumber)

